disabled_rules: # Default Rules에서 비활성화 할 규칙
- line_length
- trailing_whitespace
- vertical_whitespace
- identifier_name
- shorthand_operator
- statement_position
- file_length
- large_tuple
- attributes
- function_body_length


opt_in_rules: # 활성화 할 규칙
- weak_delegate
- vertical_whitespace_between_cases
- empty_count
- attributes
- closure_end_indentation
- closure_spacing
- collection_alignment
- convenience_type
- discouraged_object_literal
- empty_collection_literal
- empty_string
- enum_case_associated_values_count
- fatal_error_message
- force_unwrapping
- implicitly_unwrapped_optional
- literal_expression_end_indentation
- multiline_arguments
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- operator_usage_whitespace
- unneeded_parentheses_in_closure_argument
- yoda_condition


excluded: # 규칙을 적용하지 않을 경로
- ${PWD}/DerivedData
- ./**/AppDelegate.swift
- ./**/SceneDelegate.swift


analyzer_rules: # 분석 규칙
  - unused_import
