disabled_rules: # Default Rules에서 비활성화 할 규칙
- line_length
- trailing_whitespace
- vertical_whitespace
- trailing_newline
- for_where
- force_cast
- identifier_name
- implicit_getter
- shorthand_operator
- syntactic_sugar

opt_in_rules: # 활성화 할 규칙
- weak_delegate
- vertical_whitespace_between_cases

excluded: # 규칙을 적용하지 않을 경로
- DerivedData
- bridge-ios/Bridge/Application/AppDelegate.swift
- bridge-ios/Bridge/Application/SceneDelegate.swift

custom_rules:
  brace_spacing:
    name: "Brace Spacing"
    regex: "\\{[^\\s]|[^\\s]\\}" # 중괄호 양 끝에 공백이 없는 경우에 일치
    message: "중괄호 {}의 양 끝에 공백이 있어야 합니다."
    severity: warning
    

